// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriTrackAI.Data;

#nullable disable

namespace NutriTrackAI.Migrations
{
    [DbContext(typeof(NutriTrackContext))]
    partial class NutriTrackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NutriTrackAI.Models.DietaryRestriction", b =>
                {
                    b.Property<int>("DietaryRestrictionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DietaryRestrictionID"));

                    b.Property<string>("RestrictionName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("DietaryRestrictionID");

                    b.HasIndex("RestrictionName")
                        .IsUnique();

                    b.ToTable("DietaryRestrictions");

                    b.HasData(
                        new
                        {
                            DietaryRestrictionID = 1,
                            RestrictionName = "Vegan"
                        },
                        new
                        {
                            DietaryRestrictionID = 2,
                            RestrictionName = "Keto"
                        },
                        new
                        {
                            DietaryRestrictionID = 3,
                            RestrictionName = "High Protein"
                        },
                        new
                        {
                            DietaryRestrictionID = 4,
                            RestrictionName = "Gluten-Free"
                        },
                        new
                        {
                            DietaryRestrictionID = 5,
                            RestrictionName = "Dairy-Free"
                        },
                        new
                        {
                            DietaryRestrictionID = 6,
                            RestrictionName = "Nut-Free"
                        },
                        new
                        {
                            DietaryRestrictionID = 7,
                            RestrictionName = "Low Carb"
                        });
                });

            modelBuilder.Entity("NutriTrackAI.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IngredientID"));

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("IngredientID");

                    b.HasIndex("IngredientName")
                        .IsUnique();

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("NutriTrackAI.Models.MealPlan", b =>
                {
                    b.Property<int>("MealPlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MealPlanID"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("MealPlanID");

                    b.HasIndex("UserID");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("NutriTrackAI.Models.MealPlanRecipe", b =>
                {
                    b.Property<int>("MealPlanRecipeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MealPlanRecipeID"));

                    b.Property<DateTime>("MealDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MealPlanID")
                        .HasColumnType("int");

                    b.Property<int>("MealTypeID")
                        .HasColumnType("int");

                    b.Property<int>("RecipeID")
                        .HasColumnType("int");

                    b.HasKey("MealPlanRecipeID");

                    b.HasIndex("MealTypeID");

                    b.HasIndex("RecipeID");

                    b.HasIndex("MealPlanID", "MealDate", "MealTypeID")
                        .IsUnique();

                    b.ToTable("MealPlanRecipes");
                });

            modelBuilder.Entity("NutriTrackAI.Models.MealType", b =>
                {
                    b.Property<int>("MealTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MealTypeID"));

                    b.Property<string>("MealTypeName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("MealTypeID");

                    b.HasIndex("MealTypeName")
                        .IsUnique();

                    b.ToTable("MealTypes");

                    b.HasData(
                        new
                        {
                            MealTypeID = 1,
                            MealTypeName = "Breakfast"
                        },
                        new
                        {
                            MealTypeID = 2,
                            MealTypeName = "Lunch"
                        },
                        new
                        {
                            MealTypeID = 3,
                            MealTypeName = "Dinner"
                        },
                        new
                        {
                            MealTypeID = 4,
                            MealTypeName = "Snack"
                        });
                });

            modelBuilder.Entity("NutriTrackAI.Models.PantryItem", b =>
                {
                    b.Property<int>("PantryItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PantryItemID"));

                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("UnitID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PantryItemID");

                    b.HasIndex("IngredientID");

                    b.HasIndex("UnitID");

                    b.HasIndex("UserID", "IngredientID", "UnitID")
                        .IsUnique();

                    b.ToTable("PantryItems");
                });

            modelBuilder.Entity("NutriTrackAI.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RecipeID"));

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourceURL")
                        .HasColumnType("longtext");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("RecipeID");

                    b.HasIndex("UserID");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("NutriTrackAI.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeIngredientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RecipeIngredientID"));

                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("RecipeID")
                        .HasColumnType("int");

                    b.Property<int?>("UnitID")
                        .HasColumnType("int");

                    b.HasKey("RecipeIngredientID");

                    b.HasIndex("IngredientID");

                    b.HasIndex("UnitID");

                    b.HasIndex("RecipeID", "IngredientID", "UnitID")
                        .IsUnique();

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("NutriTrackAI.Models.RecipeNutrition", b =>
                {
                    b.Property<int>("RecipeID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Calories")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Carbs")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Fat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Protein")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("RecipeID");

                    b.ToTable("RecipeNutrition", (string)null);
                });

            modelBuilder.Entity("NutriTrackAI.Models.RecipeRestriction", b =>
                {
                    b.Property<int>("RecipeID")
                        .HasColumnType("int");

                    b.Property<int>("DietaryRestrictionID")
                        .HasColumnType("int");

                    b.HasKey("RecipeID", "DietaryRestrictionID");

                    b.HasIndex("DietaryRestrictionID");

                    b.ToTable("RecipeRestrictions");
                });

            modelBuilder.Entity("NutriTrackAI.Models.ShoppingList", b =>
                {
                    b.Property<int>("ShoppingListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ShoppingListID"));

                    b.Property<int>("MealPlanID")
                        .HasColumnType("int");

                    b.HasKey("ShoppingListID");

                    b.HasIndex("MealPlanID")
                        .IsUnique();

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("NutriTrackAI.Models.ShoppingListItem", b =>
                {
                    b.Property<int>("ShoppingListItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ShoppingListItemID"));

                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<bool>("IsCheckedOff")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ShoppingListID")
                        .HasColumnType("int");

                    b.Property<int?>("UnitID")
                        .HasColumnType("int");

                    b.HasKey("ShoppingListItemID");

                    b.HasIndex("IngredientID");

                    b.HasIndex("UnitID");

                    b.HasIndex("ShoppingListID", "IngredientID", "UnitID")
                        .IsUnique();

                    b.ToTable("ShoppingListItems");
                });

            modelBuilder.Entity("NutriTrackAI.Models.Unit", b =>
                {
                    b.Property<int>("UnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UnitID"));

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("UnitID");

                    b.HasIndex("UnitName")
                        .IsUnique();

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            UnitID = 1,
                            UnitName = "grams"
                        },
                        new
                        {
                            UnitID = 2,
                            UnitName = "cups"
                        },
                        new
                        {
                            UnitID = 3,
                            UnitName = "tablespoons"
                        },
                        new
                        {
                            UnitID = 4,
                            UnitName = "teaspoons"
                        },
                        new
                        {
                            UnitID = 5,
                            UnitName = "ounces"
                        },
                        new
                        {
                            UnitID = 6,
                            UnitName = "pieces"
                        });
                });

            modelBuilder.Entity("NutriTrackAI.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NutriTrackAI.Models.UserDietaryRestriction", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("DietaryRestrictionID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "DietaryRestrictionID");

                    b.HasIndex("DietaryRestrictionID");

                    b.ToTable("UserDietaryRestrictions");
                });

            modelBuilder.Entity("NutriTrackAI.Models.MealPlan", b =>
                {
                    b.HasOne("NutriTrackAI.Models.User", "User")
                        .WithMany("MealPlans")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriTrackAI.Models.MealPlanRecipe", b =>
                {
                    b.HasOne("NutriTrackAI.Models.MealPlan", "MealPlan")
                        .WithMany("MealPlanRecipes")
                        .HasForeignKey("MealPlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriTrackAI.Models.MealType", "MealType")
                        .WithMany("MealPlanRecipes")
                        .HasForeignKey("MealTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriTrackAI.Models.Recipe", "Recipe")
                        .WithMany("MealPlanRecipes")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");

                    b.Navigation("MealType");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("NutriTrackAI.Models.PantryItem", b =>
                {
                    b.HasOne("NutriTrackAI.Models.Ingredient", "Ingredient")
                        .WithMany("PantryItems")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriTrackAI.Models.Unit", "Unit")
                        .WithMany("PantryItems")
                        .HasForeignKey("UnitID");

                    b.HasOne("NutriTrackAI.Models.User", "User")
                        .WithMany("PantryItems")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Unit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriTrackAI.Models.Recipe", b =>
                {
                    b.HasOne("NutriTrackAI.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriTrackAI.Models.RecipeIngredient", b =>
                {
                    b.HasOne("NutriTrackAI.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriTrackAI.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriTrackAI.Models.Unit", "Unit")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("UnitID");

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("NutriTrackAI.Models.RecipeNutrition", b =>
                {
                    b.HasOne("NutriTrackAI.Models.Recipe", "Recipe")
                        .WithOne("RecipeNutrition")
                        .HasForeignKey("NutriTrackAI.Models.RecipeNutrition", "RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("NutriTrackAI.Models.RecipeRestriction", b =>
                {
                    b.HasOne("NutriTrackAI.Models.DietaryRestriction", "DietaryRestriction")
                        .WithMany("RecipeRestrictions")
                        .HasForeignKey("DietaryRestrictionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriTrackAI.Models.Recipe", "Recipe")
                        .WithMany("RecipeRestrictions")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietaryRestriction");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("NutriTrackAI.Models.ShoppingList", b =>
                {
                    b.HasOne("NutriTrackAI.Models.MealPlan", "MealPlan")
                        .WithOne("ShoppingList")
                        .HasForeignKey("NutriTrackAI.Models.ShoppingList", "MealPlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("NutriTrackAI.Models.ShoppingListItem", b =>
                {
                    b.HasOne("NutriTrackAI.Models.Ingredient", "Ingredient")
                        .WithMany("ShoppingListItems")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriTrackAI.Models.ShoppingList", "ShoppingList")
                        .WithMany("ShoppingListItems")
                        .HasForeignKey("ShoppingListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriTrackAI.Models.Unit", "Unit")
                        .WithMany("ShoppingListItems")
                        .HasForeignKey("UnitID");

                    b.Navigation("Ingredient");

                    b.Navigation("ShoppingList");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("NutriTrackAI.Models.UserDietaryRestriction", b =>
                {
                    b.HasOne("NutriTrackAI.Models.DietaryRestriction", "DietaryRestriction")
                        .WithMany("UserDietaryRestrictions")
                        .HasForeignKey("DietaryRestrictionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriTrackAI.Models.User", "User")
                        .WithMany("UserDietaryRestrictions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietaryRestriction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriTrackAI.Models.DietaryRestriction", b =>
                {
                    b.Navigation("RecipeRestrictions");

                    b.Navigation("UserDietaryRestrictions");
                });

            modelBuilder.Entity("NutriTrackAI.Models.Ingredient", b =>
                {
                    b.Navigation("PantryItems");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("ShoppingListItems");
                });

            modelBuilder.Entity("NutriTrackAI.Models.MealPlan", b =>
                {
                    b.Navigation("MealPlanRecipes");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("NutriTrackAI.Models.MealType", b =>
                {
                    b.Navigation("MealPlanRecipes");
                });

            modelBuilder.Entity("NutriTrackAI.Models.Recipe", b =>
                {
                    b.Navigation("MealPlanRecipes");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("RecipeNutrition");

                    b.Navigation("RecipeRestrictions");
                });

            modelBuilder.Entity("NutriTrackAI.Models.ShoppingList", b =>
                {
                    b.Navigation("ShoppingListItems");
                });

            modelBuilder.Entity("NutriTrackAI.Models.Unit", b =>
                {
                    b.Navigation("PantryItems");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("ShoppingListItems");
                });

            modelBuilder.Entity("NutriTrackAI.Models.User", b =>
                {
                    b.Navigation("MealPlans");

                    b.Navigation("PantryItems");

                    b.Navigation("Recipes");

                    b.Navigation("UserDietaryRestrictions");
                });
#pragma warning restore 612, 618
        }
    }
}
